service: project-1

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: "ap-south-1"
  stage: dev
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
        - "ses:*"
        Resource:
        - "*"

functions:
  createContact:
    handler: handler.createContact
    events:
    - http:
        path: /mail
        method: POST
